-- Convenience Manager v1.0.0
-- Execute este arquivo no SQL Editor do Supabase.

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  categoria_id bigint not null references public.categorias(id),
  nome text not null,
  descricao text,
  preco_compra numeric(14,2) not null default 0 check (preco_compra >= 0),
  margem numeric(8,2) not null default 0,
  preco_sugerido numeric(14,2) not null default 0,
  preco_venda numeric(14,2) not null default 0 check (preco_venda >= 0),
  estoque_atual numeric(14,3) not null default 0 check (estoque_atual >= 0),
  estoque_minimo numeric(14,3) not null default 0,
  imagem_url text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_produtos_categoria on public.produtos(categoria_id);
create index if not exists idx_produtos_ativo on public.produtos(ativo);

create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  nome text not null,
  cpf text unique,
  telefone text,
  cep text,
  endereco text,
  numero text,
  bairro text,
  cidade text,
  uf text,
  created_at timestamptz not null default now()
);

create table if not exists public.formas_pagamento (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.vendas (
  id bigint generated by default as identity primary key,
  cliente_id bigint references public.clientes(id),
  subtotal numeric(14,2) not null default 0,
  desconto numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  status text not null default 'finalizada' check (status in ('finalizada','cancelada')),
  created_at timestamptz not null default now()
);
create index if not exists idx_vendas_created_at on public.vendas(created_at desc);

create table if not exists public.venda_itens (
  id bigint generated by default as identity primary key,
  venda_id bigint not null references public.vendas(id) on delete cascade,
  produto_id bigint not null references public.produtos(id),
  quantidade numeric(14,3) not null check (quantidade > 0),
  preco_unitario numeric(14,2) not null,
  preco_custo numeric(14,2) not null,
  subtotal numeric(14,2) not null
);

create table if not exists public.venda_pagamentos (
  id bigint generated by default as identity primary key,
  venda_id bigint not null references public.vendas(id) on delete cascade,
  forma_pagamento_id bigint not null references public.formas_pagamento(id),
  valor numeric(14,2) not null check (valor >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.movimentacoes_estoque (
  id bigint generated by default as identity primary key,
  produto_id bigint not null references public.produtos(id),
  tipo text not null check (tipo in ('ENTRADA','VENDA','AJUSTE','PERDA','CANCELAMENTO')),
  quantidade numeric(14,3) not null,
  estoque_anterior numeric(14,3) not null,
  estoque_posterior numeric(14,3) not null check (estoque_posterior >= 0),
  custo_unitario numeric(14,2),
  venda_id bigint references public.vendas(id),
  observacao text,
  created_at timestamptz not null default now()
);
create index if not exists idx_mov_estoque_produto on public.movimentacoes_estoque(produto_id, created_at desc);

create table if not exists public.caixas (
  id bigint generated by default as identity primary key,
  valor_inicial numeric(14,2) not null default 0,
  status text not null default 'aberto' check (status in ('aberto','fechado')),
  aberto_em timestamptz not null default now(),
  fechado_em timestamptz,
  valor_final_esperado numeric(14,2),
  valor_final_informado numeric(14,2),
  diferenca numeric(14,2)
);

create unique index if not exists apenas_um_caixa_aberto
  on public.caixas ((status)) where status = 'aberto';

create table if not exists public.movimentacoes_caixa (
  id bigint generated by default as identity primary key,
  caixa_id bigint not null references public.caixas(id),
  tipo text not null check (tipo in ('VENDA','SANGRIA','SUPRIMENTO')),
  valor numeric(14,2) not null check (valor >= 0),
  venda_id bigint references public.vendas(id),
  forma_pagamento_id bigint references public.formas_pagamento(id),
  descricao text,
  created_at timestamptz not null default now()
);

insert into public.formas_pagamento(nome) values
  ('PIX'),('Espécie'),('Cartão de crédito'),('Cartão de débito')
on conflict (nome) do nothing;

insert into public.categorias(nome) values
  ('Bebidas'),('Doces'),('Salgados'),('Higiene'),('Outros')
on conflict (nome) do nothing;

-- Venda transacional: valida estoque, grava preços históricos, baixa estoque e atualiza caixa.
create or replace function public.finalizar_venda(
  p_cliente_id bigint,
  p_forma_pagamento_id bigint,
  p_itens jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item jsonb;
  v_produto public.produtos%rowtype;
  v_total numeric(14,2) := 0;
  v_venda_id bigint;
  v_qtd numeric(14,3);
  v_subtotal numeric(14,2);
  v_caixa_id bigint;
begin
  if jsonb_array_length(p_itens) = 0 then
    raise exception 'A venda precisa ter pelo menos um item.';
  end if;

  -- Primeiro bloqueia e valida todos os produtos.
  for v_item in select * from jsonb_array_elements(p_itens)
  loop
    v_qtd := (v_item->>'quantidade')::numeric;
    if v_qtd <= 0 then raise exception 'Quantidade inválida.'; end if;

    select * into v_produto
      from public.produtos
      where id = (v_item->>'produto_id')::bigint and ativo = true
      for update;

    if not found then raise exception 'Produto não encontrado ou inativo.'; end if;
    if v_produto.estoque_atual < v_qtd then
      raise exception 'Estoque insuficiente para % (disponível: %).', v_produto.nome, v_produto.estoque_atual;
    end if;
    v_total := v_total + round(v_produto.preco_venda * v_qtd, 2);
  end loop;

  insert into public.vendas(cliente_id, subtotal, desconto, total, status)
  values (p_cliente_id, v_total, 0, v_total, 'finalizada')
  returning id into v_venda_id;

  for v_item in select * from jsonb_array_elements(p_itens)
  loop
    v_qtd := (v_item->>'quantidade')::numeric;
    select * into v_produto from public.produtos where id=(v_item->>'produto_id')::bigint for update;
    v_subtotal := round(v_produto.preco_venda * v_qtd, 2);

    insert into public.venda_itens(venda_id, produto_id, quantidade, preco_unitario, preco_custo, subtotal)
    values(v_venda_id, v_produto.id, v_qtd, v_produto.preco_venda, v_produto.preco_compra, v_subtotal);

    update public.produtos set estoque_atual = estoque_atual - v_qtd, updated_at=now() where id=v_produto.id;

    insert into public.movimentacoes_estoque(produto_id,tipo,quantidade,estoque_anterior,estoque_posterior,custo_unitario,venda_id,observacao)
    values(v_produto.id,'VENDA',-v_qtd,v_produto.estoque_atual,v_produto.estoque_atual-v_qtd,v_produto.preco_compra,v_venda_id,'Venda #'||v_venda_id);
  end loop;

  insert into public.venda_pagamentos(venda_id, forma_pagamento_id, valor)
  values(v_venda_id,p_forma_pagamento_id,v_total);

  select id into v_caixa_id from public.caixas where status='aberto' order by aberto_em desc limit 1;
  if v_caixa_id is not null then
    insert into public.movimentacoes_caixa(caixa_id,tipo,valor,venda_id,forma_pagamento_id,descricao)
    values(v_caixa_id,'VENDA',v_total,v_venda_id,p_forma_pagamento_id,'Venda #'||v_venda_id);
  end if;

  return jsonb_build_object('venda_id',v_venda_id,'total',v_total);
end;
$$;

-- Como o app usa chave de servidor, o navegador nunca acessa as tabelas diretamente.
alter table public.categorias enable row level security;
alter table public.produtos enable row level security;
alter table public.clientes enable row level security;
alter table public.formas_pagamento enable row level security;
alter table public.vendas enable row level security;
alter table public.venda_itens enable row level security;
alter table public.venda_pagamentos enable row level security;
alter table public.movimentacoes_estoque enable row level security;
alter table public.caixas enable row level security;
alter table public.movimentacoes_caixa enable row level security;

-- Catálogo público via backend Flask; não é necessário criar policy anon.

revoke execute on function public.finalizar_venda(bigint,bigint,jsonb) from public, anon, authenticated;
grant execute on function public.finalizar_venda(bigint,bigint,jsonb) to service_role;
